### ISSUE TITLE
Responsive Image Assignment Requirement 

### ISSUE THREAD

**Issue by Kukk0006** [Kukk0006/mtm6201-week1#1]
@abhaysharma  I'm in group one for Web Dev II and I am working on the assignment.  I would like some clarification on how you want the image to be responsive.  I have the code so it can be, but I'm not seeing the changes when I am resizing the browser.  I assume it isn't a media query issue since it is essentially like a mini resume/business card type of thing.  If you look at my repo, I do have two different images, one of which I exported as 150 px.   The current image is much bigger with a css of max-width.  If I could get a better idea of what you are looking for in regards to this.  Thank you.

**Comment by abhaysharma** [comment]
@Kukk0006 If you have the image to be 150px max-width you are good. 150px is a small enough size that it will not need to be resized for a smaller screen.
